name: Release

on:
  release:
    types: [prereleased]

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        package: [SudoDEM2D, SudoDEM3D]

    steps:
    - uses: actions/checkout@v4

    - name: install basic 3rdlibs
      shell: bash
      run: |
        mkdir -p 3rdlib/3rdlibs/py
        cd scripts
        sh install3rd_base.sh

    - name: compile 3rdlibs
      if: false #do not compile
      shell: bash
      run: |
        cd scripts
        sh install3rdcore_sudosimlab.sh

    - name: download precompiled 3rdlibs
      shell: bash
      run: |
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/tools-${{matrix.os}}.tar.xz
        tar xf tools-${{matrix.os}}.tar.xz
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/3rdlibs-${{matrix.os}}.tar.xz
        tar xf 3rdlibs-${{matrix.os}}.tar.xz
        cd 3rdlib
        cp -rf HeaderLib/lib/* 3rdlibs/
        cp -r HeaderLib/lib/py/* 3rdlibs/py/

    - name: compile ${{matrix.package}}
      shell: bash
      run: |
        cd scripts
        sh firstCompile_${{matrix.package}}.sh

    - name: Archive compiled ${{matrix.package}}
      working-directory: ${{github.workspace}}/
      run: |
          tar cfJ ${{matrix.package}}-${{matrix.os}}.tar.xz sudodeminstall

    - name: upload compiled ${{matrix.package}}
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.package}}-${{matrix.os}}
        path: |
          ${{github.workspace}}/${{matrix.package}}-${{matrix.os}}.tar.xz

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/${{matrix.package}}-${{matrix.os}}.tar.xz
        tag: ${{ github.ref }}
        overwrite: true