name: Build SudoDEM3D

on:
  #push:
    #branches: [ci]

  pull_request:
    branches: [master]
    paths:
      - SudoDEM3D/**

env:
  BUILD_TYPE: Release

jobs:
  SudoDEM3Dbuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4

    - name: install basic 3rdlibs
      shell: bash
      run: |
        mkdir -p 3rdlib/3rdlibs/py
        cd scripts
        sh install3rd_base.sh

    - name: compile 3rdlibs
      if: false #do not compile
      shell: bash
      run: |
        cd scripts
        sh install3rdcore_sudosimlab.sh

    - name: download precompiled 3rdlibs
      shell: bash
      run: |
        mkdir -p 3rdlib/3rdlibs/py
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/tools-${{matrix.os}}.tar.xz
        tar xf tools-${{matrix.os}}.tar.xz
        cd 3rdlib
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/3rdlibs-${{matrix.os}}.tar.xz
        tar xf 3rdlibs-${{matrix.os}}.tar.xz
        cp -rf HeaderLib/lib/* 3rdlibs/
        cp -r HeaderLib/lib/py/* 3rdlibs/py/

    - name: compile SudoDEM3D
      shell: bash
      run: |
        cd scripts
        sh firstCompile_SudoDEM3D.sh

    - name: Archive compiled SudoDEM3D
      working-directory: ${{github.workspace}}/
      run: |
          tar cfJ SudoDEM3D-${{matrix.os}}.tar.xz sudodeminstall

    - name: upload compiled SudoDEM3D
      uses: actions/upload-artifact@v3
      with:
        name: SudoDEM3D-${{matrix.os}}
        path: |
          ${{github.workspace}}/SudoDEM3D-${{matrix.os}}.tar.xz


